CREATE DATABASE faceDB;
use faceDB

CREATE TABLE login_face
(
    id VARCHAR(32) NOT NULL PRIMARY KEY,
    name VARCHAR(15) NOT NULL DEFAULT '',
    id_type VARCHAR(32) NOT NULL DEFAULT '',
    channel VARCHAR(16) NOT NULL DEFAULT '',
    feature VARCHAR(4096) NOT NULL DEFAULT '',
    upload_date TIMESTAMP NOT NULL
);

CREATE TABLE varify_record
(
    id VARCHAR(32) NOT NULL PRIMARY KEY,
    name VARCHAR(15) NOT NULL DEFAULT '',
    id_type VARCHAR(32) NOT NULL DEFAULT '',
    channel VARCHAR(16) NOT NULL DEFAULT '',
    upload_date TIMESTAMP NOT NULL
);
