CREATE DATABASE faceDB CHARACTER SET utf8;
use faceDB

CREATE TABLE login_face
(
    uid VARCHAR(32) NOT NULL PRIMARY KEY,
    uid_type VARCHAR(16) NOT NULL DEFAULT '',
    name VARCHAR(15) NOT NULL DEFAULT '',
    channel VARCHAR(16) NOT NULL DEFAULT '',
    login_time VARCHAR(19) NOT NULL,
    feature VARCHAR(4096) NOT NULL DEFAULT '',
    img_path VARCHAR(4096) NOT NULL DEFAULT ''
);

CREATE TABLE check_log
(
    num INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    uid VARCHAR(32) NOT NULL,
    uid_type VARCHAR(16) NOT NULL DEFAULT '',
    name VARCHAR(15) NOT NULL DEFAULT '',
    channel VARCHAR(16) NOT NULL DEFAULT '',
    check_time VARCHAR(19) NOT NULL,
    img_path VARCHAR(4096) NOT NULL DEFAULT '',
    result TINYINT NOT NULL DEFAULT 0,
    sim FLOAT NOT NULL DEFAULT 0
);
